title: <p align="center"> Anand B Joshi </p>
logo: /assets/img/logo.png
description: 
  <p align="center">
  <a href="https://twitter.com/anand_joshii/">Twitter</a> |
  <a href="https://github.com/abj-16">GitHub</a>
  
  <br>
  I have worked in the Energy generation sector in Thermal powerplants as a Mechanical Engineer for 4 years.
  Currently I am pursuing my Masters in Artificial Intelligence and Machine Learning.
  Worked with companies like Orient Cements Ltd and Thermax Ltd.
  <br>
  </p>
show_downloads: true
theme: jekyll-theme-minimal
